# Generated by Django 5.0.3 on 2024-03-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='dish2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
