# Generated by Django 5.0.3 on 2024-03-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menuitems_dish3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='dish2',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='dish3',
        ),
    ]
