# Generated by Django 5.0.3 on 2024-03-25 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_menuitems_dish2_remove_menuitems_dish3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='description',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='dish',
            new_name='menu',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
