# Generated by Django 5.0.3 on 2024-03-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_menucategory_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reservation_day', models.CharField(max_length=15)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Menuitems',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
