# Generated by Django 5.0.3 on 2024-03-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_logger_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='logger',
            name='reservation_date',
        ),
    ]
