# Generated by Django 5.0.3 on 2024-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_logger_email_remove_logger_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='time_log',
        ),
        migrations.AddField(
            model_name='logger',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='logger',
            name='message',
            field=models.CharField(default='Enter message', max_length=500),
        ),
    ]
