# Generated by Django 5.0.3 on 2024-03-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_logger_email_alter_logger_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='logger',
            name='message',
            field=models.TextField(max_length=254),
        ),
    ]
